public enum Token {
    CLASS, EXTENDS, IMPLEMENTS, FINAL,
    PUBLIC, PRIVATE, PROTECTED, STATIC,
    FOR, WHILE, DO, CONTINUE,
    IF, ELSE, SWITCH, CASE, DEFAULT, BREAK,
    RETURN,
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_CURLY_BRACE, RIGHT_CURLY_BRACE,
    COMMA, SEMICOLON, COLON, QUOTATION_MARKS,
    PLUS, MINUS, TIMES, DIVIDE, MODULO,

    AND, OR, NOT,

    LESS, LESS_EQUALS, GREATER, GREATER_EQUALS, EQUALS, NOT_EQUALS,
    INCREMENT, DECREMENT,
    ASSIGNMENT, ADDITION_ASSIGNMENT, SUBTRACTION_ASSIGNMENT, MULTIPLICATION_ASSIGNMENT,
    DIVISION_ASSIGNMENT, MODULO_ASSIGNMENT,
    INT, FLOAT, DOUBLE, CHAR, STRING, BOOLEAN, LONG, SHORT, BYTE, VOID,
    TRUE, FALSE,
    NULL,
    NUMBER, IDENTIFIER, STRING_VALUE,
    METHOD, CLASSNAME, VARIABLE,
    ERROR
}
